name: meze-dev
channels:
  - conda-forge
  - openbiosim
dependencies:
  - python>=3.11
  - biosimspace
  - somd2
  - numpy<2
  - mdanalysis
  - openbabel
  - pygraphviz
  - rich
  - pip
  - pip:
    - -e .
