name: meze-dev
channels:
  - conda-forge
  - openbiosim
  - openbiosim/label/dev
dependencies:
  - python>=3.11
  - biosimspace
  - sire>=2026.1.0
  - openbiosim/label/dev::somd2
  - numpy<2
  - mdanalysis
  - openbabel
  - pygraphviz
  - rich
  - pip
  - pip:
    - -e .
