name: meze-dev
channels:
  - conda-forge
  - openbiosim
  - openbiosim/label/dev
dependencies:
  - python=3.12
  - openbiosim/label/dev::biosimspace
  - numpy<2
  - mdanalysis
  - openbabel
  - pygraphviz
  - rich
  - pip
  - pytest
  - pytest-cov
  - ambertools
  - flake8
  - pip:
    - -e .
