name: meze-env
channels:
  - conda-forge
  - openbiosim
  - openbiosim/label/dev
dependencies:
  - python=3.12
  - openbiosim/label/dev::biosimspace
  - openbiosim/label/dev::somd2
  - numpy<2
  - mdanalysis
  - openbabel
  - pygraphviz
  - rich
  - pip
  - pip:
      - meze @ git+https://github.com/meyresearch/meze.git@main
